# Generated by Django 4.1.3 on 2022-11-18 14:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя рассылки')),
                ('email_template', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Шаблон')),
                ('emails', models.TextField(blank=True, verbose_name='Список рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
